server:
  port: 10011
spring:
  profiles:
    active: dev
    http:
      multipart:
        max-request-size: 1024MB
        max-file-size:  1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.181.20/lxjjwo?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: yclj
    password: 83212777
  resources:
    chain:
      cache: false
logging:
  config: classpath:logback.xml
  level:
    com.lxjj.wo.mapper: debug
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.lxjj.wo.entity
pagehelper:
  reasonable: false
  helperDialect: mysql
  params: count=countSql
  supportMethodsArguments: true
